"""
https://projecteuler.net/problem=12
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

My program hangs.  It's too inefficient.
"""
function triangle(n :: Int64)
    return Int(n * (n+1) / 2)
end

function divisors(n :: Int64)
    output :: Array{Int64} = [1]
    for d in 2 : n ÷ 2
        if n % d == 0
            push!(output, d)
        end
    end
    push!(output, n)
    return output
end

function euler(z :: Int64)
    n = 2
    while true
        t = triangle(n)
        d = divisors(t)
        dl = length(d)
        println("$n $t $dl $d")
        if length(d) > z
            println()
            return (n, t, dl, d)
        end
        n += 1
    end
    nothing
end
